# Generated by Django 5.1.4 on 2025-12-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='artitem',
            name='image',
            field=models.ImageField(default='', upload_to='art_images/'),
            preserve_default=False,
        ),
    ]
