# Generated by Django 5.1.4 on 2025-12-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_remove_artitem_image_url_artitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='art_images/'),
        ),
    ]
